/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.survivalworks.api;

import org.junit.Test;
import static org.junit.if (.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
